version: 1
disable_existing_loggers: false

formatters:
  simple:
    format: '[%(asctime)s] %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%dT%H:%M:%S'
  
  json:
    format: '{"timestamp": "%(asctime)s", "name": "%(name)s", "level": "%(levelname)s", "message": "%(message)s"}'
    datefmt: '%Y-%m-%dT%H:%M:%S.%f'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  
  file:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: /var/log/kafka/consumer.log
  
  metrics:
    class: logging.FileHandler
    level: INFO
    formatter: json
    filename: /var/log/kafka/consumer_stats.log

loggers:
  kafka.consumer:
    level: INFO
    handlers: [console, metrics]
    propagate: false
  
  kafka.producer:
    level: INFO
    handlers: [console, file]
    propagate: false

root:
  level: INFO
  handlers: [console, file]
